/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthLoginRouteImport } from './routes/auth/login';
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard';
import { Route as ProtectedMaintenanceWorkOrderRouteImport } from './routes/_protected/maintenance/work-order';
import { Route as ProtectedMaintenanceRoundRouteImport } from './routes/_protected/maintenance/round';
import { Route as ProtectedMaintenanceFunctionRouteImport } from './routes/_protected/maintenance/function';
import { Route as ProtectedMaintenanceComponentUnitRouteImport } from './routes/_protected/maintenance/component-unit';
import { Route as ProtectedMaintenanceComponentTypeRouteImport } from './routes/_protected/maintenance/component-type';
import { Route as ProtectedMaintenanceComponentJobRouteImport } from './routes/_protected/maintenance/component-job';
import { Route as ProtectedGeneralAddressRouteImport } from './routes/_protected/general/address';
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AuthLoginRoute = AuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => rootRouteImport,
});
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceWorkOrderRoute = ProtectedMaintenanceWorkOrderRouteImport.update({
    id: '/maintenance/work-order',
    path: '/maintenance/work-order',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceRoundRoute = ProtectedMaintenanceRoundRouteImport.update({
    id: '/maintenance/round',
    path: '/maintenance/round',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceFunctionRoute = ProtectedMaintenanceFunctionRouteImport.update({
    id: '/maintenance/function',
    path: '/maintenance/function',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceComponentUnitRoute = ProtectedMaintenanceComponentUnitRouteImport.update({
    id: '/maintenance/component-unit',
    path: '/maintenance/component-unit',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceComponentTypeRoute = ProtectedMaintenanceComponentTypeRouteImport.update({
    id: '/maintenance/component-type',
    path: '/maintenance/component-type',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedMaintenanceComponentJobRoute = ProtectedMaintenanceComponentJobRouteImport.update({
    id: '/maintenance/component-job',
    path: '/maintenance/component-job',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedGeneralAddressRoute = ProtectedGeneralAddressRouteImport.update({
    id: '/general/address',
    path: '/general/address',
    getParentRoute: () => ProtectedRouteRoute,
});
const ProtectedRouteRouteChildren = {
    ProtectedDashboardRoute: ProtectedDashboardRoute,
    ProtectedGeneralAddressRoute: ProtectedGeneralAddressRoute,
    ProtectedMaintenanceComponentJobRoute: ProtectedMaintenanceComponentJobRoute,
    ProtectedMaintenanceComponentTypeRoute: ProtectedMaintenanceComponentTypeRoute,
    ProtectedMaintenanceComponentUnitRoute: ProtectedMaintenanceComponentUnitRoute,
    ProtectedMaintenanceFunctionRoute: ProtectedMaintenanceFunctionRoute,
    ProtectedMaintenanceRoundRoute: ProtectedMaintenanceRoundRoute,
    ProtectedMaintenanceWorkOrderRoute: ProtectedMaintenanceWorkOrderRoute,
};
const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(ProtectedRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
    AuthLoginRoute: AuthLoginRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
