/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedStockStockUsedRouteImport } from './routes/_protected/stock/stock-used'
import { Route as ProtectedStockStockTypeRouteImport } from './routes/_protected/stock/stock-type'
import { Route as ProtectedStockStockItemRouteImport } from './routes/_protected/stock/stock-item'
import { Route as ProtectedMaintenanceWorkOrderRouteImport } from './routes/_protected/maintenance/work-order'
import { Route as ProtectedMaintenanceRoundRouteImport } from './routes/_protected/maintenance/round'
import { Route as ProtectedMaintenanceFunctionRouteImport } from './routes/_protected/maintenance/function'
import { Route as ProtectedMaintenanceComponentUnitRouteImport } from './routes/_protected/maintenance/component-unit'
import { Route as ProtectedMaintenanceComponentTypeRouteImport } from './routes/_protected/maintenance/component-type'
import { Route as ProtectedMaintenanceComponentJobRouteImport } from './routes/_protected/maintenance/component-job'
import { Route as ProtectedGeneralPendingTypeRouteImport } from './routes/_protected/general/pending-type'
import { Route as ProtectedGeneralMaintClassRouteImport } from './routes/_protected/general/maint-class'
import { Route as ProtectedGeneralLocationRouteImport } from './routes/_protected/general/location'
import { Route as ProtectedGeneralJobDescriptionRouteImport } from './routes/_protected/general/job-description'
import { Route as ProtectedGeneralJobClassRouteImport } from './routes/_protected/general/job-class'
import { Route as ProtectedGeneralFollowStatusRouteImport } from './routes/_protected/general/follow-status'
import { Route as ProtectedGeneralEmployeeRouteImport } from './routes/_protected/general/employee'
import { Route as ProtectedGeneralDisciplineRouteImport } from './routes/_protected/general/discipline'
import { Route as ProtectedGeneralCounterTypeRouteImport } from './routes/_protected/general/counter-type'
import { Route as ProtectedGeneralAddressRouteImport } from './routes/_protected/general/address'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStockStockUsedRoute = ProtectedStockStockUsedRouteImport.update({
  id: '/stock/stock-used',
  path: '/stock/stock-used',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStockStockTypeRoute = ProtectedStockStockTypeRouteImport.update({
  id: '/stock/stock-type',
  path: '/stock/stock-type',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStockStockItemRoute = ProtectedStockStockItemRouteImport.update({
  id: '/stock/stock-item',
  path: '/stock/stock-item',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMaintenanceWorkOrderRoute =
  ProtectedMaintenanceWorkOrderRouteImport.update({
    id: '/maintenance/work-order',
    path: '/maintenance/work-order',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceRoundRoute =
  ProtectedMaintenanceRoundRouteImport.update({
    id: '/maintenance/round',
    path: '/maintenance/round',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceFunctionRoute =
  ProtectedMaintenanceFunctionRouteImport.update({
    id: '/maintenance/function',
    path: '/maintenance/function',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceComponentUnitRoute =
  ProtectedMaintenanceComponentUnitRouteImport.update({
    id: '/maintenance/component-unit',
    path: '/maintenance/component-unit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceComponentTypeRoute =
  ProtectedMaintenanceComponentTypeRouteImport.update({
    id: '/maintenance/component-type',
    path: '/maintenance/component-type',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceComponentJobRoute =
  ProtectedMaintenanceComponentJobRouteImport.update({
    id: '/maintenance/component-job',
    path: '/maintenance/component-job',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralPendingTypeRoute =
  ProtectedGeneralPendingTypeRouteImport.update({
    id: '/general/pending-type',
    path: '/general/pending-type',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralMaintClassRoute =
  ProtectedGeneralMaintClassRouteImport.update({
    id: '/general/maint-class',
    path: '/general/maint-class',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralLocationRoute =
  ProtectedGeneralLocationRouteImport.update({
    id: '/general/location',
    path: '/general/location',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralJobDescriptionRoute =
  ProtectedGeneralJobDescriptionRouteImport.update({
    id: '/general/job-description',
    path: '/general/job-description',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralJobClassRoute =
  ProtectedGeneralJobClassRouteImport.update({
    id: '/general/job-class',
    path: '/general/job-class',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralFollowStatusRoute =
  ProtectedGeneralFollowStatusRouteImport.update({
    id: '/general/follow-status',
    path: '/general/follow-status',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralEmployeeRoute =
  ProtectedGeneralEmployeeRouteImport.update({
    id: '/general/employee',
    path: '/general/employee',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralDisciplineRoute =
  ProtectedGeneralDisciplineRouteImport.update({
    id: '/general/discipline',
    path: '/general/discipline',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralCounterTypeRoute =
  ProtectedGeneralCounterTypeRouteImport.update({
    id: '/general/counter-type',
    path: '/general/counter-type',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralAddressRoute = ProtectedGeneralAddressRouteImport.update({
  id: '/general/address',
  path: '/general/address',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/general/address': typeof ProtectedGeneralAddressRoute
  '/general/counter-type': typeof ProtectedGeneralCounterTypeRoute
  '/general/discipline': typeof ProtectedGeneralDisciplineRoute
  '/general/employee': typeof ProtectedGeneralEmployeeRoute
  '/general/follow-status': typeof ProtectedGeneralFollowStatusRoute
  '/general/job-class': typeof ProtectedGeneralJobClassRoute
  '/general/job-description': typeof ProtectedGeneralJobDescriptionRoute
  '/general/location': typeof ProtectedGeneralLocationRoute
  '/general/maint-class': typeof ProtectedGeneralMaintClassRoute
  '/general/pending-type': typeof ProtectedGeneralPendingTypeRoute
  '/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/maintenance/component-unit': typeof ProtectedMaintenanceComponentUnitRoute
  '/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
  '/stock/stock-item': typeof ProtectedStockStockItemRoute
  '/stock/stock-type': typeof ProtectedStockStockTypeRoute
  '/stock/stock-used': typeof ProtectedStockStockUsedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/general/address': typeof ProtectedGeneralAddressRoute
  '/general/counter-type': typeof ProtectedGeneralCounterTypeRoute
  '/general/discipline': typeof ProtectedGeneralDisciplineRoute
  '/general/employee': typeof ProtectedGeneralEmployeeRoute
  '/general/follow-status': typeof ProtectedGeneralFollowStatusRoute
  '/general/job-class': typeof ProtectedGeneralJobClassRoute
  '/general/job-description': typeof ProtectedGeneralJobDescriptionRoute
  '/general/location': typeof ProtectedGeneralLocationRoute
  '/general/maint-class': typeof ProtectedGeneralMaintClassRoute
  '/general/pending-type': typeof ProtectedGeneralPendingTypeRoute
  '/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/maintenance/component-unit': typeof ProtectedMaintenanceComponentUnitRoute
  '/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
  '/stock/stock-item': typeof ProtectedStockStockItemRoute
  '/stock/stock-type': typeof ProtectedStockStockTypeRoute
  '/stock/stock-used': typeof ProtectedStockStockUsedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/_protected/general/address': typeof ProtectedGeneralAddressRoute
  '/_protected/general/counter-type': typeof ProtectedGeneralCounterTypeRoute
  '/_protected/general/discipline': typeof ProtectedGeneralDisciplineRoute
  '/_protected/general/employee': typeof ProtectedGeneralEmployeeRoute
  '/_protected/general/follow-status': typeof ProtectedGeneralFollowStatusRoute
  '/_protected/general/job-class': typeof ProtectedGeneralJobClassRoute
  '/_protected/general/job-description': typeof ProtectedGeneralJobDescriptionRoute
  '/_protected/general/location': typeof ProtectedGeneralLocationRoute
  '/_protected/general/maint-class': typeof ProtectedGeneralMaintClassRoute
  '/_protected/general/pending-type': typeof ProtectedGeneralPendingTypeRoute
  '/_protected/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/_protected/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/_protected/maintenance/component-unit': typeof ProtectedMaintenanceComponentUnitRoute
  '/_protected/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/_protected/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/_protected/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
  '/_protected/stock/stock-item': typeof ProtectedStockStockItemRoute
  '/_protected/stock/stock-type': typeof ProtectedStockStockTypeRoute
  '/_protected/stock/stock-used': typeof ProtectedStockStockUsedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/general/address'
    | '/general/counter-type'
    | '/general/discipline'
    | '/general/employee'
    | '/general/follow-status'
    | '/general/job-class'
    | '/general/job-description'
    | '/general/location'
    | '/general/maint-class'
    | '/general/pending-type'
    | '/maintenance/component-job'
    | '/maintenance/component-type'
    | '/maintenance/component-unit'
    | '/maintenance/function'
    | '/maintenance/round'
    | '/maintenance/work-order'
    | '/stock/stock-item'
    | '/stock/stock-type'
    | '/stock/stock-used'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/general/address'
    | '/general/counter-type'
    | '/general/discipline'
    | '/general/employee'
    | '/general/follow-status'
    | '/general/job-class'
    | '/general/job-description'
    | '/general/location'
    | '/general/maint-class'
    | '/general/pending-type'
    | '/maintenance/component-job'
    | '/maintenance/component-type'
    | '/maintenance/component-unit'
    | '/maintenance/function'
    | '/maintenance/round'
    | '/maintenance/work-order'
    | '/stock/stock-item'
    | '/stock/stock-type'
    | '/stock/stock-used'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/auth/login'
    | '/_protected/general/address'
    | '/_protected/general/counter-type'
    | '/_protected/general/discipline'
    | '/_protected/general/employee'
    | '/_protected/general/follow-status'
    | '/_protected/general/job-class'
    | '/_protected/general/job-description'
    | '/_protected/general/location'
    | '/_protected/general/maint-class'
    | '/_protected/general/pending-type'
    | '/_protected/maintenance/component-job'
    | '/_protected/maintenance/component-type'
    | '/_protected/maintenance/component-unit'
    | '/_protected/maintenance/function'
    | '/_protected/maintenance/round'
    | '/_protected/maintenance/work-order'
    | '/_protected/stock/stock-item'
    | '/_protected/stock/stock-type'
    | '/_protected/stock/stock-used'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stock/stock-used': {
      id: '/_protected/stock/stock-used'
      path: '/stock/stock-used'
      fullPath: '/stock/stock-used'
      preLoaderRoute: typeof ProtectedStockStockUsedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stock/stock-type': {
      id: '/_protected/stock/stock-type'
      path: '/stock/stock-type'
      fullPath: '/stock/stock-type'
      preLoaderRoute: typeof ProtectedStockStockTypeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stock/stock-item': {
      id: '/_protected/stock/stock-item'
      path: '/stock/stock-item'
      fullPath: '/stock/stock-item'
      preLoaderRoute: typeof ProtectedStockStockItemRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/work-order': {
      id: '/_protected/maintenance/work-order'
      path: '/maintenance/work-order'
      fullPath: '/maintenance/work-order'
      preLoaderRoute: typeof ProtectedMaintenanceWorkOrderRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/round': {
      id: '/_protected/maintenance/round'
      path: '/maintenance/round'
      fullPath: '/maintenance/round'
      preLoaderRoute: typeof ProtectedMaintenanceRoundRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/function': {
      id: '/_protected/maintenance/function'
      path: '/maintenance/function'
      fullPath: '/maintenance/function'
      preLoaderRoute: typeof ProtectedMaintenanceFunctionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/component-unit': {
      id: '/_protected/maintenance/component-unit'
      path: '/maintenance/component-unit'
      fullPath: '/maintenance/component-unit'
      preLoaderRoute: typeof ProtectedMaintenanceComponentUnitRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/component-type': {
      id: '/_protected/maintenance/component-type'
      path: '/maintenance/component-type'
      fullPath: '/maintenance/component-type'
      preLoaderRoute: typeof ProtectedMaintenanceComponentTypeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/component-job': {
      id: '/_protected/maintenance/component-job'
      path: '/maintenance/component-job'
      fullPath: '/maintenance/component-job'
      preLoaderRoute: typeof ProtectedMaintenanceComponentJobRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/pending-type': {
      id: '/_protected/general/pending-type'
      path: '/general/pending-type'
      fullPath: '/general/pending-type'
      preLoaderRoute: typeof ProtectedGeneralPendingTypeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/maint-class': {
      id: '/_protected/general/maint-class'
      path: '/general/maint-class'
      fullPath: '/general/maint-class'
      preLoaderRoute: typeof ProtectedGeneralMaintClassRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/location': {
      id: '/_protected/general/location'
      path: '/general/location'
      fullPath: '/general/location'
      preLoaderRoute: typeof ProtectedGeneralLocationRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/job-description': {
      id: '/_protected/general/job-description'
      path: '/general/job-description'
      fullPath: '/general/job-description'
      preLoaderRoute: typeof ProtectedGeneralJobDescriptionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/job-class': {
      id: '/_protected/general/job-class'
      path: '/general/job-class'
      fullPath: '/general/job-class'
      preLoaderRoute: typeof ProtectedGeneralJobClassRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/follow-status': {
      id: '/_protected/general/follow-status'
      path: '/general/follow-status'
      fullPath: '/general/follow-status'
      preLoaderRoute: typeof ProtectedGeneralFollowStatusRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/employee': {
      id: '/_protected/general/employee'
      path: '/general/employee'
      fullPath: '/general/employee'
      preLoaderRoute: typeof ProtectedGeneralEmployeeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/discipline': {
      id: '/_protected/general/discipline'
      path: '/general/discipline'
      fullPath: '/general/discipline'
      preLoaderRoute: typeof ProtectedGeneralDisciplineRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/counter-type': {
      id: '/_protected/general/counter-type'
      path: '/general/counter-type'
      fullPath: '/general/counter-type'
      preLoaderRoute: typeof ProtectedGeneralCounterTypeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/address': {
      id: '/_protected/general/address'
      path: '/general/address'
      fullPath: '/general/address'
      preLoaderRoute: typeof ProtectedGeneralAddressRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedGeneralAddressRoute: typeof ProtectedGeneralAddressRoute
  ProtectedGeneralCounterTypeRoute: typeof ProtectedGeneralCounterTypeRoute
  ProtectedGeneralDisciplineRoute: typeof ProtectedGeneralDisciplineRoute
  ProtectedGeneralEmployeeRoute: typeof ProtectedGeneralEmployeeRoute
  ProtectedGeneralFollowStatusRoute: typeof ProtectedGeneralFollowStatusRoute
  ProtectedGeneralJobClassRoute: typeof ProtectedGeneralJobClassRoute
  ProtectedGeneralJobDescriptionRoute: typeof ProtectedGeneralJobDescriptionRoute
  ProtectedGeneralLocationRoute: typeof ProtectedGeneralLocationRoute
  ProtectedGeneralMaintClassRoute: typeof ProtectedGeneralMaintClassRoute
  ProtectedGeneralPendingTypeRoute: typeof ProtectedGeneralPendingTypeRoute
  ProtectedMaintenanceComponentJobRoute: typeof ProtectedMaintenanceComponentJobRoute
  ProtectedMaintenanceComponentTypeRoute: typeof ProtectedMaintenanceComponentTypeRoute
  ProtectedMaintenanceComponentUnitRoute: typeof ProtectedMaintenanceComponentUnitRoute
  ProtectedMaintenanceFunctionRoute: typeof ProtectedMaintenanceFunctionRoute
  ProtectedMaintenanceRoundRoute: typeof ProtectedMaintenanceRoundRoute
  ProtectedMaintenanceWorkOrderRoute: typeof ProtectedMaintenanceWorkOrderRoute
  ProtectedStockStockItemRoute: typeof ProtectedStockStockItemRoute
  ProtectedStockStockTypeRoute: typeof ProtectedStockStockTypeRoute
  ProtectedStockStockUsedRoute: typeof ProtectedStockStockUsedRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedGeneralAddressRoute: ProtectedGeneralAddressRoute,
  ProtectedGeneralCounterTypeRoute: ProtectedGeneralCounterTypeRoute,
  ProtectedGeneralDisciplineRoute: ProtectedGeneralDisciplineRoute,
  ProtectedGeneralEmployeeRoute: ProtectedGeneralEmployeeRoute,
  ProtectedGeneralFollowStatusRoute: ProtectedGeneralFollowStatusRoute,
  ProtectedGeneralJobClassRoute: ProtectedGeneralJobClassRoute,
  ProtectedGeneralJobDescriptionRoute: ProtectedGeneralJobDescriptionRoute,
  ProtectedGeneralLocationRoute: ProtectedGeneralLocationRoute,
  ProtectedGeneralMaintClassRoute: ProtectedGeneralMaintClassRoute,
  ProtectedGeneralPendingTypeRoute: ProtectedGeneralPendingTypeRoute,
  ProtectedMaintenanceComponentJobRoute: ProtectedMaintenanceComponentJobRoute,
  ProtectedMaintenanceComponentTypeRoute:
    ProtectedMaintenanceComponentTypeRoute,
  ProtectedMaintenanceComponentUnitRoute:
    ProtectedMaintenanceComponentUnitRoute,
  ProtectedMaintenanceFunctionRoute: ProtectedMaintenanceFunctionRoute,
  ProtectedMaintenanceRoundRoute: ProtectedMaintenanceRoundRoute,
  ProtectedMaintenanceWorkOrderRoute: ProtectedMaintenanceWorkOrderRoute,
  ProtectedStockStockItemRoute: ProtectedStockStockItemRoute,
  ProtectedStockStockTypeRoute: ProtectedStockStockTypeRoute,
  ProtectedStockStockUsedRoute: ProtectedStockStockUsedRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
