/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedMaintenanceWorkOrderRouteImport } from './routes/_protected/maintenance/work-order'
import { Route as ProtectedMaintenanceRoundRouteImport } from './routes/_protected/maintenance/round'
import { Route as ProtectedMaintenanceFunctionRouteImport } from './routes/_protected/maintenance/function'
import { Route as ProtectedMaintenanceComponentTypeRouteImport } from './routes/_protected/maintenance/component-type'
import { Route as ProtectedMaintenanceComponentJobRouteImport } from './routes/_protected/maintenance/component-job'
import { Route as ProtectedGeneralAddressRouteImport } from './routes/_protected/general/address'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMaintenanceWorkOrderRoute =
  ProtectedMaintenanceWorkOrderRouteImport.update({
    id: '/maintenance/work-order',
    path: '/maintenance/work-order',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceRoundRoute =
  ProtectedMaintenanceRoundRouteImport.update({
    id: '/maintenance/round',
    path: '/maintenance/round',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceFunctionRoute =
  ProtectedMaintenanceFunctionRouteImport.update({
    id: '/maintenance/function',
    path: '/maintenance/function',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceComponentTypeRoute =
  ProtectedMaintenanceComponentTypeRouteImport.update({
    id: '/maintenance/component-type',
    path: '/maintenance/component-type',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMaintenanceComponentJobRoute =
  ProtectedMaintenanceComponentJobRouteImport.update({
    id: '/maintenance/component-job',
    path: '/maintenance/component-job',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedGeneralAddressRoute = ProtectedGeneralAddressRouteImport.update({
  id: '/general/address',
  path: '/general/address',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/general/address': typeof ProtectedGeneralAddressRoute
  '/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/general/address': typeof ProtectedGeneralAddressRoute
  '/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/_protected/general/address': typeof ProtectedGeneralAddressRoute
  '/_protected/maintenance/component-job': typeof ProtectedMaintenanceComponentJobRoute
  '/_protected/maintenance/component-type': typeof ProtectedMaintenanceComponentTypeRoute
  '/_protected/maintenance/function': typeof ProtectedMaintenanceFunctionRoute
  '/_protected/maintenance/round': typeof ProtectedMaintenanceRoundRoute
  '/_protected/maintenance/work-order': typeof ProtectedMaintenanceWorkOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/general/address'
    | '/maintenance/component-job'
    | '/maintenance/component-type'
    | '/maintenance/function'
    | '/maintenance/round'
    | '/maintenance/work-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/general/address'
    | '/maintenance/component-job'
    | '/maintenance/component-type'
    | '/maintenance/function'
    | '/maintenance/round'
    | '/maintenance/work-order'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/auth/login'
    | '/_protected/general/address'
    | '/_protected/maintenance/component-job'
    | '/_protected/maintenance/component-type'
    | '/_protected/maintenance/function'
    | '/_protected/maintenance/round'
    | '/_protected/maintenance/work-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/work-order': {
      id: '/_protected/maintenance/work-order'
      path: '/maintenance/work-order'
      fullPath: '/maintenance/work-order'
      preLoaderRoute: typeof ProtectedMaintenanceWorkOrderRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/round': {
      id: '/_protected/maintenance/round'
      path: '/maintenance/round'
      fullPath: '/maintenance/round'
      preLoaderRoute: typeof ProtectedMaintenanceRoundRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/function': {
      id: '/_protected/maintenance/function'
      path: '/maintenance/function'
      fullPath: '/maintenance/function'
      preLoaderRoute: typeof ProtectedMaintenanceFunctionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/component-type': {
      id: '/_protected/maintenance/component-type'
      path: '/maintenance/component-type'
      fullPath: '/maintenance/component-type'
      preLoaderRoute: typeof ProtectedMaintenanceComponentTypeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/maintenance/component-job': {
      id: '/_protected/maintenance/component-job'
      path: '/maintenance/component-job'
      fullPath: '/maintenance/component-job'
      preLoaderRoute: typeof ProtectedMaintenanceComponentJobRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/general/address': {
      id: '/_protected/general/address'
      path: '/general/address'
      fullPath: '/general/address'
      preLoaderRoute: typeof ProtectedGeneralAddressRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedGeneralAddressRoute: typeof ProtectedGeneralAddressRoute
  ProtectedMaintenanceComponentJobRoute: typeof ProtectedMaintenanceComponentJobRoute
  ProtectedMaintenanceComponentTypeRoute: typeof ProtectedMaintenanceComponentTypeRoute
  ProtectedMaintenanceFunctionRoute: typeof ProtectedMaintenanceFunctionRoute
  ProtectedMaintenanceRoundRoute: typeof ProtectedMaintenanceRoundRoute
  ProtectedMaintenanceWorkOrderRoute: typeof ProtectedMaintenanceWorkOrderRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedGeneralAddressRoute: ProtectedGeneralAddressRoute,
  ProtectedMaintenanceComponentJobRoute: ProtectedMaintenanceComponentJobRoute,
  ProtectedMaintenanceComponentTypeRoute:
    ProtectedMaintenanceComponentTypeRoute,
  ProtectedMaintenanceFunctionRoute: ProtectedMaintenanceFunctionRoute,
  ProtectedMaintenanceRoundRoute: ProtectedMaintenanceRoundRoute,
  ProtectedMaintenanceWorkOrderRoute: ProtectedMaintenanceWorkOrderRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
